---
title: "R Notebook"
output: html_notebook
---

## Context

#### Business intelligence and data-driven decision making

* What insights can the business/organisation gain from your analysis and how will your analysis help the business/organisation make better decisions? 

This data can be used to assist Visit Scotland in decision making on where more support may be required for tourism assets and what may benefit from further publicity to increase popularity.

Some of the most popular activities in terms on money generated and visits taken are meals out, shopping, outdoor leisure and visits with friends and family. In terms of spend per visit special personal events and days out to spas/health clubs generate a high value while being low in terms of the number of visits. By attempting to increase the marketing and prevalence of these types of activity it should be possible to increase the overall spend, improving the tourism economy for Scotland as a whole.

Cities are the most popular location with tourists to Scotland and the order of all locations appears to correlate well with the expected population of these locations. This may well relate to the most common reason for visits being to see friends and family and these locations often having more potential tourist activities. Tourism assets in smaller locations may benefit from the increased awareness Visit Scotland could provide to grow their business (especially those in close proximity to cities).

When looking at the method of transport used car is by far the most popular with almost double the number of visits compared to all other methods combined. This bodes well for locations without good public transport links though these may still suffer from their location to some extent. Working with public transport providers may be able to create a mutually beneficial arrangement to improve public transport use and access to tourism destinations.

The most popular type of accommodation in all areas is hotels though popularity of all types varies by location. This information may be of use to Visit Scotland in supporting new types of accommodation by created (building new hotels, opening new camp sites etc.) with expected popularity data based on similar types in similar locations.

By demographics we can see there are certain groups who make the most trips to Scotland and spend the most money. Identification of these keys demographics may be beneficial to targeted marketing campaigns to draw more visitors. Without a full breakdown of how these numbers are summed we cannot fully make this decision (would be able to run a regression model with the original survey data). We can see however that the median spending is highest for;

* People with access to a car

* People aged 25-34 and 45-54

* Individuals without children

* Employed people

* Married couples

* Those in social grades AB and C2.

Viewing regional tourism we can see similar patterns between England and Scotland those trips are generally longer for those based in England. The Highlands, Edinburgh and Glasgow are particularly popular and Visit Scotland should work with assets in this area to provide the best experiences to tourists. A major impact Visit Scotland could have is providing increased awareness of locations in less popular counties to attempt to grow business.

In general tourism is increasing year on year for the majority of locations and activities. However with only 7 years of full data prior to the Covid-19 pandemic it is difficult to predict with any accuracy tourism levels for the future. With 2020 being so disrupted and 2021 not much better any predictions based on 2019 data for the future are unlikely to have a high level of accuracy. We would need to settle in for a few more years and assess recovery from the pandemic before we can make good predictions again. However trends increasing prior to this is a promising sign that recovery should occur.



#### Domain knowledge and the business context

* Briefly describe the business/organisation and where your analysis fits within its aims/activity. 


To help Visit Scotland with its goals of realising the potential of the tourism assets throughout Scotland we want to look at data on a range of topics such as;

* What types of activities are visited most and which generate the most revenue?
* What types of location are visited most and which generate the most revenue?
* What methods of transport do tourists use?
* What demographics of people make up the tourist population?
* Which counties of Scotland are most popular with tourists?
* What type of accommodation is more popular in various types of area?

With a better understanding of these type of statistics we can understand what are is more or less popular and from there, determine where more support may be required to help meet demand and where further development is needed. Using this, Visit Scotland can work with private businesses, public agencies and local authorities to improve visitor experience and help various tourism assets reach their potential.

## Data

#### Internal and external data sources

* Briefly describe your data sources and which were internal (provided by the organisation) and external (not sourced from the organisation's data)

The data sets used are from statistics.gov.scot. Data was collected using a survey methodology and due to Covid-19 collection was disrupted in 2020 (bar accommodation data).

The data available is all summary data grouped by year and various categories. Due to this any averages will use median rather than mean to minimise the effect of any outlier values.

### _Activities, location, transport and demographic data_

This data was generated using over 35,000 interviews with adults over 16, resident in England, Wales and Scotland during weekly survery waves between 2013 and 2019.

A tourism day trip is defined as taking part in a listed activity, which takes more than 3 hours out of the home and is not done regularly. The activity must not be done in the place of living or work (if started after work). Trips specifically to visitor attractions, live sporting events and special public events did not have to meet all of these criteria.

### _Accomodation data_

This data was produced from a survey completed by the accomodation provider between 2011 and 2021. This survery is sent out monthly and participation of providers varies over time. Geographic locations are defined as follows;

* Large Urban Areas (settlements of over 125,000 people)
* Other Urban Areas (settlements of 10,000 to 124,999 people)
* Accessible Small Towns (settlements of 3,000 to 9,999 people and within 30 minutes drive of a settlement of 10,000 or more) 
* Remote Small Towns (settlements of 3,000 to 9,999 people and with a drive time of over 30 minutes to a settlement of 10,000 or more) 
* Accessible Rural (settlements of less than 3,000 people and within 30 minutes drive of a settlement of 10,000 or more) 
* Remote Rural (settlements of less than 3,000 people and with a drive time of over 30 minutes to a settlement of 10,000 or more)

15 rows only showed a low sample size of data (primarily small hotels and hostels), these will be discounted for the sake of using more reliable data.

### _Regional tourism data_

This data is gathered from surveys and looks at overnight trips taken for any purpose between 2013 and 2019. Some 100,000 residents of Great Britain were contacted and those who had returned from an overnight trip in the past 4 weeks were asked to describe this trip, from which this data was generated.

### _Geospatial data_

Another set of data was downloaded with matching values for Scottish counties so that the geospatial data from this could be joined to the regioanl tourism data to plot maps. This was also accessed from statistics.gov.scot.

#### Types of data

* What kind of data did you work with? E.g. categorical and numerical data and their sub-types.

I worked with both categorical and numerical data.

#### Data formats

* What format did your data come in? E.g. all downloaded flat files (CSV) or any data from APIs, scraping etc.

Downloaded data came in the form of 6 .csv files and 1 shape file for geospatial data.

#### Data quality and bias

* Briefly describe the quality of the data and whether you have any reasons to suggest the data is biased e.g. only data from a specific demographic even though a broader demographic would be of interest to the organisation.

The data is somewhat biased as it relies on individuals completing surveys which is more likely for certain individuals than others, potentially skewing the data in some way.

The data available is not the original survey data which could have been used to find out more about the type of individuals who use tourism activities and where they go. The data has been grouped and collated for each year and by the specific focus of the table in question meaning we cannot examine whether more people in specific age groups visit certain types of activity or location for example. This could be of more use in targeted marketing. This has been done for data ethics pruposes rather than releasing any potential personal information.

## Ethics

#### Ethical issues in data sourcing and extraction

* Do you have any ethical concerns regarding the sourcing and extraction of your data? 

The data has been released in grouped and without and personal information. At the levels involved there are no real ethical implications to dealing with personal data as this has been obscured by the scale of data.

#### Ethical implications of business requirements

* Are there any ethical implications of the business requirements?

Data should not be used to specifically target people based on any protected characteristics.

## Analysis

#### Stages in the data analysis process

* What were the main stages in your data analysis process?

Cleaning data to ensure it is in the most useful form, ensuring numeric data is in that format rather than character, pivoting data to a more useful format and joining data where applicable. This also included some renaming of columns to make them more readable for myself.

Creating tables and visualizations of data sets to see any trends and plot important data.

Carrying out mutations on data sets to plot median and average data over years where individuals years data was not desired.

Analysis of the tables and visualizations created. 

#### Tools for data analysis

* What were the main tools you used for your analysis?

R
tidyverse
ggplot

#### Descriptive, diagnostic, predictive and prescriptive analysis

* Please report under which of the below categories your analysis falls **and why** (can be more than one) 

**Descriptive Analytics** tells you what happened in the past.

The majority of analysis falls under descriptive analysis. What activities, locations, methods of transport etc. were most popular.

**Diagnostic Analytics** helps you understand why something happened in the past.

Some of this descriptive analysis can be used to make diagnostic analysis. With the most popular reason for visits to an activity being visits to family and friends we can see a correlation with the most popular locations visited being those with high expectated populations (large towns and cities).

